Point plus extended
LSST-strong-lensing/slsim pull request #107
Opened 2023-12-05 18:14 UTC by nkhadka21

Made documentation of variable_lens_injection() function more clear.

2023-12-05 20:31 UTC, sibirrer requested changes
Thank you! Please describe what "time_series_images" are and the other parts that are in exposure_data. Thank you!

2023-12-08 19:43 UTC, nkhadka21 commented on slsim/Util/param_util.py
> +def transformmatrix_to_pixelscale(tranform_matrix, rotation_matrix=None):
> I don't really understand the inputs here. You don't need any knowledge about the rotation to compute the pixel scale (determinants are invariant under rotations)

Yes, you are right. I just removed rotation matrix from here.

2023-12-08 19:49 UTC, nkhadka21 commented on slsim/Util/param_util.py
> +    class ImageWrapper:
> I am not sure I understand the purpose of this class. Can you elaborate on this?

The add_object() function takes a dp0 image object as a input. This dp0 image object contains all the information like image_array, psf, pixel scale etc. So, if some of wants to use images other than dp0 in add_object function, they can use their own image, psf, pixel scale in SLSimObject and this object is compatible with add_object() function. So, we do not need to create any other function for this case.

2023-12-09 02:07 UTC, sibirrer approved these changes

2023-12-09 03:52 UTC, merged