Magnitude support
LSST-strong-lensing/slsim pull request #142
Opened 2024-03-23 17:24 UTC by Henry-Best-01

Working on testing magnitude support for AGN variability.

2024-03-25 15:42 UTC, Henry-Best-01 commented
I am not sure why codecov/project is failing. If you have any insight, I would appreciate it so I can help fix the problem!

2024-03-25 15:44 UTC, sibirrer commented
@Henry-Best-01 hmm, I don't know either. All your changes have been covered with tests, so I think it's good to go from that regard

2024-03-29 21:29 UTC, nkhadka21 requested changes
Hi @Henry-Best-01 , Thank you very much for this PR! I have few minor comments. Please look at them.

2024-03-29 21:29 UTC, nkhadka21 commented on slsim/Util/astro_util.py
> +    is_magnitude=False,
Can you make default is_magnitude = True because magnitude is the conventional unit in SLSim?

2024-03-29 21:29 UTC, nkhadka21 commented on slsim/Util/astro_util.py
> +    is_magnitude=False,
Here also can you make default is_magnitude = True?

2024-04-08 15:23 UTC, Henry-Best-01 commented
I changed all references of "is_magnitude" to "normal_magnitude_variance", since the default units are to be magnitude. I also removed "new_" from all user defined means and standard deviations.

2024-04-08 16:05 UTC, nkhadka21 approved these changes
Hi @Henery, thank you very much for these changes. It looks good to merge. For another step, I think you can compute light curve in a particular band using mean wavelength of that band (this is a simplest thing we can do).

2024-04-08 16:08 UTC, merged