Adding support for speclite and general broadband filters
LSST-strong-lensing/slsim pull request #152
Opened 2024-04-12 21:10 UTC by Henry-Best-01

Allows calculation of agn response function using speclite filter Allows user defined filters to be created and used with agn response functions Allows conversion of any filters to source plane where reprocessing must take place Allows unit conversion between any astropy units
Added a plot in jupyter notebook showing a simple usage of these functions

2024-04-16 13:43 UTC, nkhadka21 commented
Hi @Henry-Best-01 , thank you very much for this PR! What you have done is great. Did this PR gives quasar light curve in a specific band directly from variability class? If not, it would be great if you could connect all your development to variability class (mainly passing light curve in specified band to variability class instead of intrisic signal). Thank you!

2024-04-16 13:44 UTC, nkhadka21 reviewed
Hi @Henry-Best-01 , thank you very much for this PR! What you have done is great. Did this PR gives quasar light curve in a specific band directly from variability class? If not, it would be great if you could connect all your development to variability class (mainly passing light curve in specified band to variability class instead of intrisic signal). Thank you!

2024-04-23 16:46 UTC, sibirrer commented
@ajshajib it looks like none of the PRs execute a coverage report. Is there something broken there or did we reach a limit for the free version? Thank you!

2024-04-25 21:46 UTC, ajshajib commented
@Henry-Best-01, can you kindly pull and merge from the main branch? After that, the coverage report will start working for this PR.

2024-05-03 18:03 UTC, nkhadka21 requested changes
Hi @Henry-Best-01 , thank you very much for this PR! it seems like this work is almost at the end. However, I have some suggestions for managing the code. Currently Variability class looks very crowded with mix the mixture of many things. So, I have suggested to break the code in different part and put them in different functions outside of the Variability class and call those functions whenever needed.

2024-05-20 14:12 UTC, nkhadka21 reviewed
@Henry-Best-01 , thank you very much for this update! We are very close to the completion of this PR. I have still some minor comments. Please look at them.

2024-05-20 14:12 UTC, nkhadka21 commented on slsim/Sources/SourceVariability/variability.py
> +    def parse_kwargs_for_lamppost_reprocessed_model(self):
This function is still inside the Variability class. Is it possible to move this function outside of variability class? If it is necessary to put this function inside the variability class, I am ok with this.

2024-05-20 14:12 UTC, nkhadka21 commented on slsim/Sources/SourceVariability/variability.py
> +    def reprocess_with_lamppost_model(self):
This function is also inside the variability class. Is it possible to move this function outside of the variability class. If it is necessary to put this function inside the variability class, I am ok with this.

2024-06-13 21:11 UTC, nkhadka21 commented
Hi @Henry-Best-01, I noticed a conflict here. I hope this is not very difficult to resolve in your side.

2024-06-20 11:26 UTC, Henry-Best-01 commented
Sorry for the delay! It's been very busy for me lately. I will try to resolve the conflict and set this up as we discussed last month.

2024-06-26 16:17 UTC, nkhadka21 commented
Hi @Henry-Best-01 , the CI/build  is failing because of the very small skyarea used in that particular test. I have updated this. Please synchronize your branch with main and it should work. Thank you!

2024-07-16 20:29 UTC, nkhadka21 approved these changes
Hi @Henry-Best-01 , thank you very much for these updates! Looks very good. I approve this PR.

2024-07-16 20:30 UTC, merged