Implemented realistic SN host galaxy offsets.
LSST-strong-lensing/slsim pull request #203
Opened 2024-07-16 21:22 UTC by cmistick

- Implemented realistic SN Ia offsets within host galaxies based on observational sample from Wang et al. 2013 in `supernovae_host_galaxy_offset()`
- Updated corresponding testing function  `test_supernovae_host_galaxy_offset()`

2024-07-17 16:56 UTC, nkhadka21 requested changes
Hi @cmistick, thank you very much for this PR! This looks very good. I have some comments. Please address these comments and ping me when you are ready for next review.

2024-07-17 16:56 UTC, nkhadka21 commented on slsim/Sources/galaxy_catalog.py
> +        position_angle.append(np.random.uniform(0, 360))
This must have astropy unit. Otherwise astropy function will consider it is in radian.

2024-07-17 16:56 UTC, nkhadka21 commented on slsim/Sources/galaxy_catalog.py
> +    return ra_off, dec_off
return ra_off.value, dec_off.value?

2024-07-17 17:27 UTC, nkhadka21 requested changes

2024-07-17 17:27 UTC, nkhadka21 commented on slsim/Sources/galaxy_catalog.py
> +def supernovae_host_galaxy_offset(host_galaxy_catalog):
This function is more suitable in supernovae_sample.py file.

2024-07-17 19:43 UTC, cmistick commented on slsim/Sources/galaxy_catalog.py
> +        offsets.append(offset_ratios[i] * list(host_galaxy_catalog["angular_size"])[i])
When implementing astropy units here, as well as on line 38 below, I am getting: UnitConversionError: 'Unit("rad")' is not a scaled version of 'Unit(dimensionless)', and similarly, UnitConversionError: 'Unit("deg")' is not a scaled version of 'Unit(dimensionless)'. Without the units included, the plot I have of the offsets and the corresponding host radii seems to be correct, given the distribution. For now I will commit the other changes I have made.

2024-07-18 13:39 UTC, nkhadka21 approved these changes
Hi @cmistick, thank you very much for this update! This looks wonderful. I approve it.

2024-07-18 13:40 UTC, merged