Querying massive galaxies as potential deflectors
LSST-strong-lensing/slsim pull request #251
Opened 2024-09-14 21:16 UTC by Vibhore-ARIES

In this PR, I have added a script(s) to SLSim, to query massive elliptical galaxies and identify which of them can act as potential deflectors based on the angular cross section, source luminosity function and their magnitudes and redshift etc.

The following scripts are added in this PR:
1) 'query_galaxies_as_deflectors.py' to slsim/Deflectors/
2) srcprop.py to slsim/
3) 'srclensprop.py' to slsim/
4) 'example_query_galaxies_as_deflectors.ipynb' to notebooks
5) 'test_query_galaxies_as_deflectors.py' to slsim/tests/tests_Deflectors.

2024-09-18 13:08 UTC, nkhadka21 commented
Hi @Vibhore-ARIES , Thank you very much for this PR!  This PR has CI failure and also other fail. When you make iyt to pass these test, I will then review it.

2024-09-19 12:30 UTC, Vibhore-ARIES commented
> Hi @Vibhore-ARIES , Thank you very much for this PR! This PR has CI failure and also other fail. When you make iyt to pass these test, I will then review it.

Hi @nkhadka21, thanks. Yes, I am fixing those issues.

2024-10-01 13:07 UTC, nkhadka21 requested changes

2024-10-01 13:07 UTC, nkhadka21 commented on slsim/Deflectors/query_galaxies_as_deflectors.py
> +    background_source,
As we discussed, we should find potential deflector galaxies (mostly massive elliptical) from the DC2 catalog. Then, you can use these selected deflectors in LensPop.

2025-02-04 15:39 UTC, nkhadka21 requested changes
Hi @Vibhore-ARIES , thank you very much for this PR! I have some minor comments. Please look into them. Also, it would be great if you could reduce the size of the test_DP0_catalog.csv. You might want to reduce the number of rows to 50 if possible?

2025-02-04 15:39 UTC, nkhadka21 commented on slsim/Deflectors/massive_deflectors_DP0p2.py
> +    # Compute fracDev for each galaxy to classify ellipticals
Might be helpful to provide full name for fracDev?

2025-02-04 15:39 UTC, nkhadka21 commented on slsim/Deflectors/massive_deflectors_DP0p2.py
> +    id_massive = np.where(Mag_r_sdss < -22)[0]
Do you want to have hard coded magnitude cut? Might be reasonable to have magnitude cut as an input?

2025-02-04 15:39 UTC, nkhadka21 commented on slsim/Deflectors/massive_deflectors_DP0p2.py
> +    # convert the effective radius to arcsec
Might be helpful to mention original unit and then how you converted them to arcsec.

2025-02-04 15:39 UTC, nkhadka21 commented on slsim/LsstSciencePipeline/lsst_science_pipeline.py
> +    catalog within a specified region of the sky, defined by right ascension
documentation format.

2025-02-04 15:39 UTC, nkhadka21 commented on slsim/LsstSciencePipeline/lsst_science_pipeline.py
> +    results : pandas.dataframe
Can you make it astropy table for the consistancy?

2025-02-04 15:43 UTC, nkhadka21 commented on notebooks/DP0_massive_ellipticals_params.ipynb
> +{
<p>Can you remove this error? You can update your lenstronomy and this error will be solved.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/LSST-strong-lensing/slsim/pull/251/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='0'/>

2025-02-05 11:42 UTC, Vibhore-ARIES commented on slsim/Deflectors/light2mass.py
> +    MabsB = MabsB - 5.0 * np.log10(Dlum / 10)
Hi @nkhadka21 , thank for these comments.
I have changed the comment now.

2025-02-05 11:43 UTC, Vibhore-ARIES commented on slsim/Deflectors/light2mass.py
> +    Mabsr = mrSDSS - 5.0 * np.log10(Dlum / 10)
Now the luminosity distance is in kpc, hence I have removed that factor.

2025-02-05 11:44 UTC, Vibhore-ARIES commented on slsim/Deflectors/massive_deflectors_DP0p2.py
> +    params:
I have changed and adopted the documented format from slsim. Please check if it is fine.

2025-02-05 11:45 UTC, Vibhore-ARIES commented on slsim/Deflectors/massive_deflectors_DP0p2.py
> +#!/usr/bin/env python
Yes, actually the column names used are specific to DP0.2 object catalogs, hence I have kept the name.

2025-02-05 11:46 UTC, Vibhore-ARIES commented on slsim/Deflectors/massive_deflectors_DP0p2.py
> +    params:
changed

2025-02-05 11:49 UTC, Vibhore-ARIES commented on slsim/Deflectors/massive_deflectors_DP0p2.py
> +    """Caculate the parameters for a galaxy using the HSM moments.
done

2025-02-05 11:49 UTC, Vibhore-ARIES commented on slsim/Deflectors/massive_deflectors_DP0p2.py
> +    magnitude = -2.50 * np.log10(flux) + 31.4
done.

2025-02-05 11:50 UTC, Vibhore-ARIES commented on slsim/Deflectors/massive_deflectors_DP0p2.py
> +    """This function identifies potential lensing galaxies (deflectors) from
done.

2025-02-05 11:50 UTC, Vibhore-ARIES commented on slsim/Deflectors/massive_deflectors_DP0p2.py
> +    -- DP0_table: astropy table
since it is specific to DP0 here, I have not changed it.

2025-02-05 11:50 UTC, Vibhore-ARIES commented on slsim/Deflectors/massive_deflectors_DP0p2.py
> +    # Compute fracDev for each galaxy to classify ellipticals
done

2025-02-05 11:51 UTC, Vibhore-ARIES commented on slsim/Deflectors/massive_deflectors_DP0p2.py
> +    # convert the effective radius to arcsec
done.

2025-02-05 11:51 UTC, Vibhore-ARIES commented on slsim/Deflectors/massive_deflectors_DP0p2.py
> +    id_massive = np.where(Mag_r_sdss < -22)[0]
done

2025-02-05 11:51 UTC, Vibhore-ARIES commented on slsim/LsstSciencePipeline/lsst_science_pipeline.py
> +    results : pandas.dataframe
done.

2025-02-06 21:14 UTC, nkhadka21 requested changes
Hi @Vibhore-ARIES , thank you very much! It looks very good to me. I have few minor comments for requirements.txt. Please look into them.

2025-02-06 21:14 UTC, nkhadka21 commented on requirements.txt
> +#scipy<=1.13.1
Is it necessary to downgrade scipy? If there is any incompatibility between scipy and your new code, there might be a way to change your code so that they will be compatible?

2025-02-06 21:14 UTC, nkhadka21 commented on requirements.txt
> +git+https://github.com/Vibhore-ARIES/kcorrect.git
We do not put personally git repo in the requirement. Please change it to kcorrect pip installable verson.

2025-02-14 05:37 UTC, Vibhore-ARIES commented on requirements.txt
> +git+https://github.com/Vibhore-ARIES/kcorrect.git
Changed it to pip installable version.

2025-02-14 05:37 UTC, Vibhore-ARIES commented on requirements.txt
> +#scipy<=1.13.1
could not find a fix to this, will update once I get something.

2025-02-17 21:48 UTC, nkhadka21 commented on requirements.txt
> +git+https://github.com/Vibhore-ARIES/kcorrect.git
Hi @Vibhore-ARIES , I think this is still in your personal repo.

2025-02-18 11:08 UTC, Vibhore-ARIES commented on requirements.txt
> +git+https://github.com/Vibhore-ARIES/kcorrect.git
Hi @nkhadka21, I am changing it but the PR fails some code coverage tests, which I guess is due to some other routines which I am not changing at all. I am not sure whats causing it and how to fix this.

2025-03-24 22:05 UTC, nkhadka21 approved these changes
Hi @Vibhore-ARIES , thank you very much for this PR! It looks good to me.

2025-03-24 22:05 UTC, merged